name: Pick Presenter
on:
  push:
    branches:
      - main

jobs:
  pick-presenter:
    runs-on: ubuntu-latest
    if: github.actor == 'isabel-noh'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SECRET_API_KEY }}

      - name: Pick Presenter Randomly
        id: pick_presenter
        run: echo "::set-output name=name::$(shuf -n 1 names.txt)"

      - name: README.md Update
        run: |
          sed -i "/| ---- |/a | 2   |    |           |        | ${{ steps.pick_presenter.outputs.name }}              |   |" README.md

      - name: Commit & Push
        run: |
          git config --global user.email 'nohhyunjeong93@gmail.com'
          git config --global user.name 'isabel-noh'

          git add README.md
          git commit -m "Update README.md"
          git push
